name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10]
    steps:
    - name: Login to Heroku
      uses: actions/heroku@master
      env:
        secrets : ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: Push to Heroku
      uses: actions/heroku@master
      env:
        secrets : ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a hello-gh-actions web
    - name: Deploy to Heroku
      uses: actions/heroku@master
      env:
        secrets : ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a hello-gh-actions web
